### ISSUE TITLE
./setup.sh: not found

### ISSUE THREAD

**Issue by TheBdouilleur** [MycroftAI/mycroft-precise#137]
Hi Everyone,
I have just discovered Mycroft.ai and it seems fantastic!
I am trying to perform a Source Install on a docker container running Debian 10.                                       The git-cloning and the dependencies-install have worked just fine, but running `./setup.sh` returns me the following error:
```sh
./setup.sh: line 43: sudo: command not found
```
I tried `sh setup.sh`, `bash setup.sh` and running `chmod +x` before the command, and restarting both the shell and the container, but it keeps printing the same error.
Oh and by the way, is it possible to install it directly on the system, rather than a virtual environment ?

Thank you for your help

**Comment by MatthewScholefield** [comment]
The problem is as it suggests, minimal docker containers don't have sudo installed. You can fix it by installing sudo with something like `apt-get install -y sudo` inside your docker container (or as a command in your `Dockerfile`). Alternatively, instead of running `setup.sh`, you can perform the same steps to install it globally with something like:

```bash
apt-get install -y python3-pip curl libopenblas-dev python3-scipy cython libhdf5-dev python3-h5py portaudio19-dev swig libpulse-dev libatlas-base-dev

cd path/to/mycroft-precise
pip3 install -e runner/
pip3 install -e .
```

**Comment by TheBdouilleur** [comment]
Thank you very much! I used the alternate series of commands and at first sight, it seems to work.
