### ISSUE TITLE
I found  'precise.vectorization.load_vector' do not be implemented

### ISSUE THREAD

**Issue by sushipan** [MycroftAI/mycroft-precise#189]
This method  'load_vector' do not   implement ! Anyone can help me ?

**Comment by MatthewScholefield** [comment]
Hi, I don't understand the question. Please share full error messages or try to describe it with more details.

**Comment by sushipan** [comment]
Sorry ,  I found it at the master branch ! please close this issue!
I was used the "dev" branch , And the "dev" branch do not have this method's   implement.

**Comment by sushipan** [comment]
The following method

def load_vector(name: str, vectorizer: Callable = vectorize) -> np.ndarray:
    """Loads and caches a vector input from a wav or npy file"""
    import os

    save_name = name if name.endswith('.npy') else os.path.join('.cache', str(abs(hash(pr))),
                                                                vectorizer.__name__ + '.' + name + '.npy')

    if os.path.isfile(save_name):
        return np.load(save_name)

    print('Loading ' + name + '...')
    os.makedirs(os.path.dirname(save_name), exist_ok=True)

    vec = vectorizer(load_audio(name))
    np.save(save_name, vec)
    return vec

**Comment by sushipan** [comment]
If this method still using at the version== 0.3?
I trying to make this project support multiple keywords . If I success , I will feed back

**Comment by MatthewScholefield** [comment]
Oh, do you need it because of [this line in `load_inhibit`](https://github.com/MycroftAI/mycroft-precise/blob/04053a58393e3b8067cb6628a6b3cb03c9f231d2/precise/train_data.py#L153). If this is what you are talking about, `load_inhibit` isn't actually used anymore so the entire function can be deleted. As you can tell, if someone were to try running the trainer with `load_inhibit` it would cause an error because it became broken in a refactor.

If you still need the behavior of `load_vector` let me know what specifically you need it for and I can help.

**Comment by MatthewScholefield** [comment]
Also, if you are trying to support multiple keywords, [this issue](https://github.com/MycroftAI/mycroft-precise/issues/24#issuecomment-408194375) might be helpful.

**Comment by sushipan** [comment]
Thank you !
