### ISSUE TITLE
how to envaluate SNR when using precise-add-noise?

### ISSUE THREAD

**Issue by shipleyxie** [MycroftAI/mycroft-precise#51]
look into code ,found { default noise_min is 0, and noise_max is 0.4}
after doing `adjust_noise=audio_volume * noise_data / noise_volume`
and here come my question: how to  compute the average SNR among the whole generated noise-added dataset?

**Comment by MatthewScholefield** [comment]
Could you explain your question a little more? If we assume the source audios are 100% signal (no initial background noise), then since it is a random distribution, the average signal-to-noise ratio would be halfway in-between: `(noise_max + noise_min) / 2`. Although, technically, SNR might refer to the power of the audio which means there could technically be a slight difference.

**Comment by shipleyxie** [comment]
i have record 20 wake-up-word ,and i use precise-add-noise to add different type of noise(bus stop , factory,park ..) . and i want to evaluate the portion signal to noise at the generated noise data set,
like WSJ data set while using FaNT to add noise ,i got Avg.SNR(db):5.61

**Comment by MatthewScholefield** [comment]
To help understand the question, why do you want to know/evaluate the signal to noise at the generated noise data set (the one that is combined)?

The purpose of the `precise-add-noise` script is to mix noise into a relatively clean dataset to make it more immune to noises. The script does the following:
 - Calculates the average volume of both the wake-word samples and the raw noise
 - Scales the raw noise to be the same volume as the wake-word sample
 - Combines the adjusted raw noise with the wake-word sample using the volume level you specify (a random value each time between 0.0 and 0.4)

**Comment by MatthewScholefield** [comment]
Unfortunately, SNRs vary quite a lot in how they are implemented so it's not really a good idea to compare them. I'm also not sure exactly what SNR in the context of another wake word detector would mean. You should be able to run both algorithms on the same dataset, especially since `precise-add-noise` just creates a new dataset folder that includes the noise audio in the dataset. And perhaps you can also just use FaNT and one of their algorithms to detect the signal to noise ratio.

If you really want to compare the numbers, you can see how precise uses these values [in the code here](https://github.com/MycroftAI/mycroft-precise/blob/dev/precise/scripts/add_noise.py#L87).

Let me know if this helps.

**Comment by shipleyxie** [comment]
I appreciate the quick response to this. 
and it do help a lot.
